<?php

namespace AppBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMarkUser($user_id, $product_id)
	    {
				 $conn = $this->getEntityManager()->getConnection();

				    $sql = '
				        SELECT * FROM evaluation e
				        WHERE e.user_id = :user_id
			        	AND e.product_id = :product_id
				        ';
				    $stmt = $conn->prepare($sql);
				    $stmt->execute(['user_id' => $user_id, 'product_id' => $product_id]);

				    
				    return $stmt->fetchAll();

	        /* Ici on cherche si l'utilisateur a déjà noté un produit spécifique > si sa note se trouve dans la bdd
	        $qb = $this->createQueryBuilder('e')
	            ->andWhere('e.user = :user_id')
	           	->andWhere('e.product = :product_id')
	            ->setParameter('user', $user_id)
	            ->setParameter('product', $product_id)
	            ->getQuery();

	        return $qb->execute();*/
	    }
}



